language: java
deploy:
  provider: releases
  api_key:
    secure: XKGXo6US3pFv1FYmifPqtYJkzm3eFmE7Ey1bD8fklMQlOs1AbxmbNqvJh5NDYxtMBeA2aWt3JghVPlEL+P4dCtuYghkbrt8yu+O8zk1nTDs9EZHhGweiPOEm2wu0LV4qD2Kxl4JyG7UUM4IxE/D1FRjoMbPTAyTfznAwc9JNOOlHQcJ7i0a2bGRrImdO8L67OkO4sJ7sD8B5XgLfjTdbW2UsCv//ya+mNbYfiJ/83bSignCbspIcwddZQ+wajO0D9l/YV7wrj4a+2774xHMEVfqI9DFrOi6Eaif2FTnhSP4XHozbMUBYMdg+h54/lD/SlWmUd36P++ljf6bkPohz2+zCgtw9kF20ejnZ7ex0GheLk8VElolCwUXV0HpoCLACD7BeJqcV+/hpxE28vQjLFo9EgsBcfO+MPI2y/wIjkxyY7HK1qKd/dOfRWrYg7kef9xuF11YuxBqiBaDYkNgpwemLbH/w8nQVffJhkmrTDeUcJ5fATwLkRDmv1CUywWs7U4iRjH9YhrVuyr0yPoJ6xH+gn/eUiFIJH6/wu9VB9V9zIK0ynyCA/Umx4fdHvu/v8tTKFZ/hvl3LV9hM8i4/AAwHDkO/zs0dXPE6+sZhJAupu29fORC5Ex8RzhoQ+uVc7EitHB8a7gX4XrXOCgrfjPl/jZrWwxZuWtKrX0cQFI0=
  file: build/libs/*
  skip_cleanup: true
  file_glob: true
  on:
    all_branches: true
    repo: xebialabs-community/xld-gitlab-artifact-resolver-plugin
    tags: true
notifications:
  slack:
    secure: FwmXyYHsCtAyIoPejdD97+qKS9zuhsSDz/Dnd8tNvUam2imaTImx9YG0QE47SLsq1UigI6Jz8IHAK9uWZSasO9ivU7qG8JmXrDh4fHS1vQeELKmjIBJ7O9eJgx1JAhB62Tvg31r9C5HtXTY+dKmw9KO/vLrhfWyzitGRETUjURNthCMFGDp6fAzKCfq9L9T9oCAGBtf3FG2yfoHfbNLN19yyccAFIzBV7u5hZarZy60Odlrol8w0FGFZmAXTHjLaMzKQ+YnQ2V+wKZHItJaY+dgf/dLWNvbpzCX419FxdbjA1iPIvdPL3WjjhoCplVGh7PYK9e6ygud1g18e5NpjSy71wM3Zd6OYbjnEc6Otq4Q84ctqGBIUuVOP6iHolM9cDTGVWAOaKWgu0vhhKyVoSvbS3BgVZHNVCEuR24oYDUXOpNp2zkeBibYc2zC3PF26X6cpyiUIF3prrmbL+ig38hssAaZzNQxxt2x+mHAwqKNClZAfuvHPhVuLFzVX0E5goMF9RjdabfFmiXj32fQDdd8HrPVuavAnmoRMU24YnaP9AKKvvlnFknn+xYaCEKvOd0bDSDCuY7YhyNoOLT85RAmc7Wc+njiZQtlUwv8wBQmaKwG3m/Fr3biP6qnp3E6XxW49krLwYzs/csqVOA/8GiykHqljycli8l5S8HX0VrA=
